environment                     = "dev"
account_number                  = "295446674139"
role_assumed_arn                = "arn:aws:iam::295446674139:role/UK-MKT-DEV-GLUE-ROLE-CASE12585936411"
terraform_bucket_name           = "eu-central1-dev-uk-snowfall-terraform-295446674139"
connector_profile_name          = "UK-SNowFall-ServiceNow-Connector-Prod"
aws_role_to_assume              = "arn:aws:iam::295446674139:role/UK-MKT-SNowfall-Dev-Deploy-Service-Role"
meraki_schedule                 = "cron(0 0 31 2 ? *)"
newrelic_10min_schedule         = "cron(0 0 31 2 ? *)"
newrelic_5min_schedule          = "cron(0 0 31 2 ? *)"
newrelic_1am_schedule           = "cron(0 0 31 2 ? *)"
stage_name                      = "dev"
ncr_soap_service_now_create_url = "https://osbcert-ha.ncrvoyix.com/ext/CSDI/HSRStandardSyncRestReq/ServiceRequest/CreateServiceRequest"
ncr_soap_service_now_update_url = "https://osbcert-ha.ncrvoyix.com/ext/CSDI/HSRStandardSyncRestReq/ServiceRequest/UpdateServiceRequest"


