environment             = "nprod"
account_number          = "404060908217"
role_assumed_arn        = "arn:aws:iam::404060908217:role/UK-MKT-NProd-GLUE-ROLE"
terraform_bucket_name   = "eu-central1-nprod-uk-snowfall-terraform-404060908217"
connector_profile_name  = "UK-SnowFall-ServiceNow-Prod"
aws_role_to_assume      = "arn:aws:iam::404060908217:role/UK-MKT-SNowfall-NProd-Deploy-Service-Role"
meraki_schedule         = "cron(0 0 31 2 ? *)"
newrelic_10min_schedule = "cron(0 0 31 2 ? *)"
newrelic_5min_schedule  = "cron(0 0 31 2 ? *)"
newrelic_1am_schedule   = "cron(0 0 31 2 ? *)"
smartsheet_6am_schedule = "cron(0 0 31 2 ? *)"
stage_name              = "nprod"
# ncr_soap_service_now_create_url = "https://osbcert-ha.ncrvoyix.com/ext/CSDI/HSRStandardSyncRestReq/ServiceRequest/CreateServiceRequest"
# ncr_soap_service_now_update_url = "https://osbcert-ha.ncrvoyix.com/ext/CSDI/HSRStandardSyncRestReq/ServiceRequest/UpdateServiceRequest" 

