environment             = "prod"
account_number          = "868442188363"
role_assumed_arn        = "arn:aws:iam::868442188363:role/UK-MKT-SNowfall-Prod-GLUE-SERV-ROLE"
terraform_bucket_name   = "eu-central1-prod-uk-snowfall-terraform-868442188363"
connector_profile_name  = "UK-SnowFall-ServiceNow-Prod"
aws_role_to_assume      = "arn:aws:iam::868442188363:role/UK-MKT-SNowfall-Prod-Deploy-Service-Role"
meraki_schedule         = "cron(0 1 * * ? *)"
newrelic_10min_schedule = "rate(10 minutes)"
newrelic_5min_schedule  = "cron(5 * * * ? *)"
newrelic_1am_schedule   = "cron(0 1 * * ? *)"
smartsheet_6am_schedule = "cron(0 6 * * ? *)"
stage_name              = "prod"

