name: Core Delta Lake Deployment

on:
  workflow_dispatch:  # Allows manual trigger
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        options:
        - dev
        - nprod
        - prod

jobs:
  terraform:
    concurrency:
      group: ${{ github.event.inputs.environment == 'dev' && 'deploy-development' || github.event.inputs.environment == 'nprod' && 'deploy-nprod' || github.event.inputs.environment == 'prod' && 'deploy-production' || 'default' }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      # Dynamically assign the role to assume based on the environment
      AWS_ROLE_TO_ASSUME: ${{ github.event.inputs.environment == 'dev' && secrets.AWS_ROLE_TO_ASSUME_DEV || github.event.inputs.environment == 'nprod' && secrets.AWS_ROLE_TO_ASSUME_NPROD || github.event.inputs.environment == 'prod' && secrets.AWS_ROLE_TO_ASSUME_PROD }}
      STATE_BUCKET: ${{ github.event.inputs.environment == 'dev' && secrets.STATE_BUCKET_DEV || github.event.inputs.environment == 'nprod' && secrets.STATE_BUCKET_NPROD || github.event.inputs.environment == 'prod' && secrets.STATE_BUCKET_PROD }}
      VAR_FILE: ${{ secrets.VAR_FILE }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python 3
      run: sudo apt-get update && sudo apt-get install -y python3

    - name: Install boto3
      run: python3 -m pip install boto3

    - name: Print Variable Values
      run: |
        echo "ENVIRONMENT: ${{ github.event.inputs.environment }}"
        echo "AWS_ROLE_TO_ASSUME: ${{ env.AWS_ROLE_TO_ASSUME }}"
        echo "STATE_BUCKET: ${{ env.STATE_BUCKET }}"
        echo "VAR_FILE: ${{ env.VAR_FILE }}"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActions
        web-identity-token-file: ${{ steps.oidc-token.outputs.token }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.4

    - name: Running the Core Delta Lake Stage
      run: |
        cd terraform/core_delta_lake
        terraform init -backend-config="bucket=${{ env.STATE_BUCKET }}"
        terraform plan -var-file=${{ env.VAR_FILE }} -out=tfplan
        terraform apply -auto-approve tfplan
      env:
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Running the Other Resources Stage
      run: |
        cd terraform/other_resources
        terraform init -backend-config="bucket=${{ env.STATE_BUCKET }}"
        terraform plan -var-file=${{ env.VAR_FILE }} -out=tfplan
        terraform apply -auto-approve tfplan
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
