name: Glue Workflow Deployment

on:
  push:
    branches:
      - dev
      - main
    tags:
      - v*
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ENVIRONMENT: ${{ github.ref == 'refs/heads/dev' && 'dev' ||
      github.ref == 'refs/heads/main' && 'nprod' || startsWith(github.ref, 'refs/tags/v') && 'prod' }}
  VAR_FILE: ${{ github.ref == 'refs/heads/dev' && '../dev.tfvars' ||
      github.ref == 'refs/heads/main' && '../nprod.tfvars' ||
      startsWith(github.ref, 'refs/tags/v') && '../prod.tfvars' }}

concurrency:
  group: ${{ github.ref == 'refs/heads/dev' && 'deploy-development' ||
        github.ref == 'refs/heads/main' && 'deploy-nprod' ||
        startsWith(github.ref, 'refs/tags/v') && 'deploy-production' || 'default' }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: initialise
        uses: ./.github/composite/initialise_job.yml

      - name: Running the Glue Resources Stage
        run: |
          cd terraform/glue_resources
          terraform init -backend-config="bucket=${{ env.STATE_BUCKET }}"
          terraform plan -var-file=${{ env.VAR_FILE }} -out=tfplan
          terraform apply -auto-approve tfplan
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Running the Other Resources Stage
        run: |
          cd terraform/other_resources
          terraform init -backend-config="bucket=${{ env.STATE_BUCKET }}"
          terraform plan -var-file=${{ env.VAR_FILE }} -out=tfplan
          terraform apply -auto-approve tfplan
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
