name: 'PR Enhancer'
on:
  pull_request:
    branches:
      - dev
      - main
    types: [opened, synchronize]
    
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ENVIRONMENT: ${{ github.base_ref == 'dev' && 'dev' ||
                  github.base_ref == 'main' && 'prod' }}
  VAR_FILE: ${{ github.base_ref == 'dev' && '../dev.tfvars' ||
                github.base_ref == 'dev' && '../prod.tfvars' }}

jobs:
  attach_tf_plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Initialise
        uses: ./.github/composite/initialise_job

      - name: Load AWS Role and State Bucket
        id: load_env
        run: |
          echo "Loading AWS_ROLE_TO_ASSUME and STATE_BUCKET from VAR_FILE_AWS..."
          VAR_FILE_AWS="${{ github.base_ref == 'dev' && 'terraform/dev.tfvars' ||
                            github.base_ref == 'main' && 'terraform/prod.tfvars' }}"
          
          AWS_ROLE_TO_ASSUME=$(grep 'aws_role_to_assume' "$VAR_FILE_AWS" | cut -d '=' -f2 | tr -d ' "')
          STATE_BUCKET=$(grep 'terraform_bucket_name' "$VAR_FILE_AWS" | cut -d '=' -f2 | tr -d ' "')

          echo "AWS_ROLE_TO_ASSUME=${AWS_ROLE_TO_ASSUME}" >> $GITHUB_ENV
          echo "STATE_BUCKET=${STATE_BUCKET}" >> $GITHUB_ENV

      - name: Print Variable Values
        run: |
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "AWS_ROLE_TO_ASSUME: $AWS_ROLE_TO_ASSUME"
          echo "STATE_BUCKET: $STATE_BUCKET"
          echo "VAR_FILE: $VAR_FILE"
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          web-identity-token-file: ${{ steps.oidc-token.outputs.token }}
        
      - name: Terraform Plan
        run: |
          terraform init -backend-config="bucket=${{ env.STATE_BUCKET }}"
          terraform plan -var-file=${{ env.VAR_FILE }} -no-color
        continue-on-error: true
        
      - name: Comment PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outputs.stdout }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outputs.stdout }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outputs.stdout }}\``;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform checks in directory '${{ matrix.directory }}'\n` + output
            })
